name: poly_kv_shared_preferences
description: SharedPreferences adapter for PolyKV.
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.10.0
  flutter: '>=3.35.0'

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  poly_kv: ^0.1.0
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.26.0
  very_good_analysis: ^10.2.0
