name: omni_kv_example
publish_to: none

environment:
  sdk: ^3.11.0
  flutter: '>=3.35.0'

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: any
  hive_ce: any
  omni_kv: any
  omni_kv_hive_ce: any
  omni_kv_secure_storage: any
  omni_kv_shared_preferences: any
  shared_preferences: any
