name: poly_kv_workspace

packages:
  - packages/**
  - example

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  format:apply:
    run: dart format .
    description: Format all Dart files.

  format:check:
    run: dart format --output=none --set-exit-if-changed .
    description: Check formatting.

  analyze:
    run: melos exec -- dart analyze .
    description: Analyze all packages.

  test:
    run: melos exec --dir-exists=test -- dart test
    description: Run all tests.
