name: omni_kv_workspace
publish_to: none

environment:
  sdk: ^3.10.0

workspace:
  - packages/omni_kv
  - packages/omni_kv_shared_preferences
  - packages/omni_kv_hive_ce
  - packages/omni_kv_secure_storage
  - example

dev_dependencies:
  lints: ^6.1.0
  melos: ^7.8.1
  very_good_analysis: ^10.2.0

melos:
  categories:
    packages:
      - packages/**
    examples:
      - example

  scripts:
    format:apply:
      run: dart format .
      description: Format all Dart files.

    format:check:
      run: dart format --output=none --set-exit-if-changed .
      description: Check formatting.

    analyze:
      run: melos exec -- dart analyze .
      description: Analyze all packages.

    # --- UPDATE THESE TEST SCRIPTS ---

    test:
      run: melos run test:dart && melos run test:flutter
      description: Run all tests in the workspace correctly.

    test:dart:
      run: melos exec --dir-exists=test --no-flutter -- dart test
      description: Run tests for pure Dart packages.

    test:flutter:
      run: melos exec --dir-exists=test --flutter -- flutter test
      description: Run tests for Flutter packages.
