name: omni_kv_hive_ce
description: Hive CE adapter for the OmniKV framework.
version: 0.1.0

homepage: https://github.com/puntbyte/omni_kv_workspace
repository: https://github.com/puntbyte/omni_kv_workspace/tree/main/packages/omni_kv_hive_ce
issue_tracker: https://github.com/puntbyte/omni_kv_workspace/issues

topics:
  - hive
  - hive-ce
  - key-value
  - storage
  - database

environment:
  sdk: ^3.10.0

resolution: workspace

dependencies:
  hive_ce: ^2.19.3
  omni_kv: ^0.1.0

dev_dependencies:
  test: ^1.26.0
  very_good_analysis: ^10.2.0