name: omni_kv_shared_preferences
description: SharedPreferences adapter for the OmniKV framework.
version: 0.2.0

homepage: https://github.com/puntbyte/omni_kv_workspace
repository: https://github.com/puntbyte/omni_kv_workspace/tree/main/packages/omni_kv_shared_preferences
issue_tracker: https://github.com/puntbyte/omni_kv_workspace/issues

topics:
  - shared-preferences
  - key-value
  - storage
  - preferences

environment:
  sdk: ^3.11.0
  flutter: '>=3.35.0'

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  omni_kv: ^0.2.0
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  omni_kv_testing: ^0.2.0
  test: ^1.30.0
  very_good_analysis: ^10.3.0
