name: omni_kv_secure_storage
description: Flutter secure storage adapter for the OmniKV framework.
version: 0.1.0

homepage: https://github.com/puntbyte/omni_kv_workspace
repository: https://github.com/puntbyte/omni_kv_workspace/tree/main/packages/omni_kv_secure_storage
issue_tracker: https://github.com/puntbyte/omni_kv_workspace/issues

topics:
  - secure-storage
  - key-value
  - security
  - encryption
  - keychain

environment:
  sdk: ^3.10.0
  flutter: '>=3.35.0'

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^10.3.1
  omni_kv: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  omni_kv_testing: any
  test: ^1.26.0
  very_good_analysis: ^10.2.0